"""Rename landing_socials to socials

Revision ID: 55b9c3ac0389
Revises: d4d39730656f
Create Date: 2023-03-10 22:12:38.881915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b9c3ac0389'
down_revision = 'd4d39730656f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('landing_socials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_socials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('href', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='landing_socials_pkey')
    )
    op.drop_table('socials')
    # ### end Alembic commands ###
