"""Add cv table

Revision ID: 69a5ee081cbc
Revises: 15775f254f1d
Create Date: 2023-03-13 23:07:18.583057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69a5ee081cbc'
down_revision = '15775f254f1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('during', sa.Integer(), nullable=False),
    sa.Column('at', sa.Text(), nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv')
    # ### end Alembic commands ###
