"""Add about table

Revision ID: b35cccb3f86c
Revises: 2dfbce1c42ec
Create Date: 2023-03-13 22:18:19.926402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35cccb3f86c'
down_revision = '2dfbce1c42ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('who_am_i', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('outside_of_work', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about')
    # ### end Alembic commands ###
